module.exports = function (grunt) {    'use strict';    grunt.initConfig({
  "mojito":{
    "context":"",
    "version":"0.5"
  },
  "debug":{
    "remoteDebug":false,
    "liveEdit":false,
    "httpPort":8665,
    "instrument":{
      "instrumentIgnoreDir":["mojito"],
      "instrumentIgnoreFileRegex":["^mojito.*.js$",
      "^LazyLoad.*.js$",
      "loader.*.js"]
    }
  },
  "push":{
    "packages":[]
  },
  "rt":{
    "iconfile":"",
    "devorship":"dev",
    "simordev":"simulator"
  },
  "package":{
    "iossdk":"6.0",
    "apilevel":14
  },
  "launch":{
    "devicefamily":"iphone"
  },
  "ci":{
    "svn":"",
    "branch":""
  },
  "deploy":{
    "appfolder":[],
    "instancename":""
  }
});};